config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

    has_many :book_genres
    has_many :genres, through: :book_genres

    scope :finished, ->{ where.not(finished_on: nil) }
    scope :recent, ->{ where('finished_on > ?', 2.days.ago) }
    scope :search, ->(keyword){ where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present?}
    scope :filter, ->(name){ 
      joins(:genres).where('genres.name = ?', name) if name.present?
    }


  before_save :set_keywords

  def finished?
    finished_on.present?
  end

  protected
  	def set_keywords
  		self.keywords = [title, author, description].map(&:downcase).join(' ')
  	end
end

app/models/book_genre.rb
class BookGenre < ActiveRecord::Base
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :book_genres
	has_many :books, through: :book_genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
  	render text: "hello, world!"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.includes(:genres).search(params[:keyword]).filter(params[:filter])
    @genres = Genre.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
        format.js
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :amazon_id,
                                                  { genre_ids: []}, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def image_from_amazon(amazon_id)
    image_tag "http://images.amazon.com/images/P/#{amazon_id}.01.ZTZZZZZZ.jpg"
  end
end

app/views/books/_book.html.erb
<li class="row rating-<%= book.rating %>">
            <div class="col-sm-3">
              <a href="#" target="_blank">
                <%= image_from_amazon(book.amazon_id) %>
              </a>
              <p class="text-center rating"><strong><%= book.rating %></strong>/5</p>
            </div>

            <div class="col-sm-9">
              <h3><a href="#"><%= book.title %></a></h3>
              <p class="text-muted"><em>Written by <%= book.author %></em></p>

              <div>
                <p>
                  <%= book.description %>
                </p>
              </div>
              <span>
              <% book.genres.each do |genre| %>
                <%= link_to genre.name, '#', class: 'label label-primary' %>
                <% end %>
              </span>
            </div>
          </li>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amazon_id %><br>
    <%= f.text_field :amazon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
$('.book-list').prepend('<%=j render @book %>');
$('#new_book').trigger('reset');
$('.book-form').slideUp();

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">

  <h1>Reading List</h1>

  <ol class="breadcrumb">
    <li class="active">
      Books
    </li>
  </ol>

  <div class='row'>
    <div class='col-sm-12'>
      <p>
        <form>
          <legend>Search</legend>
          <div class='col-xs-4'>
            <input type='text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Keyword' >
          </div>
        </form>
      </p>
      <p class='pull-right'>
        <a href='#' id='show-form' class='btn btn-primary'>New Book Form</a>
      </p>
    </div>
  </div>

  <hr>

  <div class='col-sm-12 book-form'>
    <p>
      <%= form_for(Book.new, remote: true, html: { class: 'horizontal-form' }) do |f| %>
      <legend>New Book</legend>

      <div class='col-sm-5'>
        <div class='form-group'>
           <label class='form-group'>
           <label class='col-sm-2 control-label'>Genre</label>
           <div class='col-sm-10'>
            <%= f.select :genre_ids,
              @genres.map { |g| [g.name, g.id] }, {}, {multiple: true} %>
            </div>
        </div>

        <br>

        <div class='form-group'>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
        </div>
        <div class='form-group'>
          <%= f.text_field :author, class: 'form-control', placeholder: 'Author' %>
        </div>
        <div class='form-group'>
          <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
        </div>
        <div class='form-group'>
          <%= f.text_field :amazon_id, class: 'form-control', placeholder: 'Amazon ID' %>
        </div>

        <div class='form-group'>
          <legend>Rating</legend>
          <% (1..5).each do |rating| %>
            <label class='radio-inline'>
              <%= rating %><%= f.radio_button :rating, rating %>
            </label>
          <% end %>
        </div>

        <div class='form-group'>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>
    </p>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <ul class="list-unstyled book-list">

  <%= render @books %>

  </ul>
    </div>
    <div class="col-sm-4">
      <h2>Genres</h2>
      <ul class="list-unstyled">
        <% @genres.each do |genre| %>
          <li>
          <%= link_to genre.name, books_path(filter: genre.name), class: 'label label-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Amazon:</strong>
  <%= @book.amazon_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ZombiesTwoReadingList</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="UTF-8">
</head>
<body>
  <%= yield %>
</body>